headerimage_conf_form:
  path: /headerbar/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Headerbar\Controller\HeaderimageController::index'
    # Needed to work with tab system
    _legacy_controller: AdminHeaderbar
    _legacy_link: AdminHeaderbar
