services:
  _defaults:
    public: true

  prestashop.module.headerbar.form.type.headerimage_text:
    class: 'PrestaShop\Module\Headerbar\Form\HeaderimageFormType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  prestashop.module.headerbar.form.headerimage_text_data_configuration:
    class: 'PrestaShop\Module\Headerbar\Form\HeaderimageTextDataConfiguration'
    arguments: ["@prestashop.adapter.legacy.configuration"]

  prestashop.module.headerbar.form.headerimage_text_form_data_provider:
    class: 'PrestaShop\Module\Headerbar\Form\HeaderimageTextFormDataProvider'
    arguments:
      - '@prestashop.module.headerbar.form.headerimage_text_data_configuration'

  prestashop.module.headerbar.form.headerimage_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.headerbar.form.headerimage_text_form_data_provider'
      - 'PrestaShop\Module\Headerbar\Form\HeaderimageFormType'
      - 'Configuration'

  PrestaShop\Module\Headerbar\Controller\HeaderimageController:
    # Using autowire will inject services in the constructors automatically
    autowire: true
    # Using autoconfigure with controllers that extend AbstractController will handle method parameter injection and subscribed services
    autoconfigure: true
    # If your controller class doesn't extend AbstractController you should add this tag manually so you benefit from method parameters injection
    tags: ['controller.service_arguments']
